name: streamverse_player
description: StreamVerse Flutter Video Player SDK
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.8.0
  exo_player_flutter: ^0.7.0
  http: ^1.1.0
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

