apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    name: platform
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: media
  labels:
    name: media
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: cdn
  labels:
    name: cdn
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    name: observability
    istio-injection: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
  labels:
    name: data
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: telecom
  labels:
    name: telecom
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: network-services
  labels:
    name: network-services

