server:
  host: 0.0.0.0
  port: "8080"
  read_timeout: 5s
  write_timeout: 10s

database:
  uri: "mongodb://localhost:27017"
  database_name: "streaming-service"
  max_pool_size: 100
  min_pool_size: 10
  connect_timeout: 10s

jwt:
  secret_key: "supersecretkey"

logging:
  level: "info"
  development: false

content_service_addr: "localhost:50051"
payment_service_addr: "localhost:50052"
