apiVersion: v1
kind: Namespace
metadata:
  name: streamverse
  labels:
    name: streamverse
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: streamverse-staging
  labels:
    name: streamverse
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: streamverse-dev
  labels:
    name: streamverse
    environment: development

